version: "3.8"

services:
  bootcampProjectDb:
    container_name: bootcamp-Db
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=bootcamp-Db

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27018:27017"
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=12345

